services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    env_file:
      - .env                              # load OLLAMA_BASE_URL and other vars
    restart: unless-stopped              # auto‑recover on failure
    depends_on:
      ollama:
        condition: service_healthy       # wait until Ollama is healthy
    networks:
      - deepseek_net

  ollama:
    image: ollama/ollama:0.1.42          # pin to a specific version
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:11434/health"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - deepseek_net

volumes:
  ollama_data:

networks:
  deepseek_net:
    driver: bridge
